### ISSUE TITLE
Memory leak in client.getValue

### ISSUE THREAD

**Issue by Mikmak2000** [ubidots/ubidots-esp8266#25]
Using the client.getValue function will cause the ESP to reboot after 50+ runs.
It seems that there is no free() in client.getValue but it is there in the other getValue functions.

**Comment by mariacarlinahernandez** [comment]
Hello @Mikmak2000,

Effectively, the method produce a memory leak into the board, I was missing the `free(data)` in the method. The issue is already fixed in the following PR #26

Please @woakas, review the PR to merge and solve the issue.
