### ISSUE TITLE
sendAll(bool type) doesn't return true on success

### ISSUE THREAD

**Issue by baskapteijn** [ubidots/ubidots-esp8266#28]
Unlike what is stated in the doxygen header:

```
/**
 * Send all data of all variables that you saved
 * @reutrn true upon success, false upon error.
 */
bool Ubidots::sendAll(bool type) {
```
It returns false (0) on success when transmitting data:

```
OK|OK|OK|OK
0   <- false!
```
Can this be confirmed and corrected in the Doxygen header, assuming that 1 is returned on failure?

**Comment by jotathebest** [comment]
To be fixed in the next release, closing accordingly
