### ISSUE TITLE
Error using "ubidots.get"

### ISSUE THREAD

**Issue by RamonMartins** [ubidots/ubidots-esp8266#36]
I got this error when used the GetValueHTTP.ino. I just changed the Constants

![error1](https://user-images.githubusercontent.com/18702896/69283094-8459d300-0bca-11ea-864c-0d62c72dd076.png)
![error2](https://user-images.githubusercontent.com/18702896/69283093-8459d300-0bca-11ea-9029-1185895de19b.png)
![error3](https://user-images.githubusercontent.com/18702896/69283622-807a8080-0bcb-11ea-891e-87fefbee0305.png)

**Comment by jotathebest** [comment]
this error is related with the ESP8266 2.6 version, please download the latest version of our library.

**Comment by astro100** [comment]
I have the same error, where it works for a bit then I get either Exception (3) or (29). What is the last known working combination of this repository and the ESP8266 core?

**Comment by jotathebest** [comment]
Hi there @astro100, the last version of the ESP8266 library that probed to work is 2.6.

All the best

**Comment by jotathebest** [comment]
We have released an update for some reported issues using the GET method at #41
