### ISSUE TITLE
not able to send context data using sendTLATE function

### ISSUE THREAD

**Issue by BJSingh** [ubidots/ubidots-esp8266#4]
Sir, I have tried this new library for nodemcu and it works great. When i tried to send data using sendHTTP function i was able to send multiple data (5 variables) with context but it takes about more than 80 seconds for uploading data. But when i used sendTLATE function i was able to send multiple data in less than 20 seconds but was not able to send context data. I also tried by removing null from: 
void add(char *variable_id, float value, char *ctext = NULL);
Also can you please explain how sendTLATE function is uploading data to Ubidots because i haven't found any data in Ubidots API documentation!!

![sendtlate snapshot](https://cloud.githubusercontent.com/assets/5358553/16706873/d68ab1b2-45da-11e6-9e35-861da38fedfe.jpg)

**Comment by Metavix** [comment]
@BJSingh Tlate function also can send context, you just need to put the context like this:
add("Variable_name", value, "$lat=1.2323$lng=1.3223");

The timing to send variables is very long, i will try to find any solution to that, thank you for the report.
Best regard,
Metavix

**Comment by BJSingh** [comment]
@Metavix Thanks, I tried and It's working!!
