### ISSUE TITLE
Compile errors re time functions

### ISSUE THREAD

**Issue by philbowles** [ubidots/ubidots-esp8266#44]
You call time functions. Where in the source do you include <time.h> I looked in several .h files for the "obvious" places but got fed up before finding it. A friend has a problem with compile errors:

`D:\Arduino\libraries\ubidots-esp8266\src\UbiTcp.cpp: In member function 'bool UbiTCP::_syncronizeTime()':
D:\Arduino\libraries\ubidots-esp8266\src\UbiTcp.cpp:294:28: error: 'time' was not declared in this scope
time_t now = time(nullptr);
^
D:\Arduino\libraries\ubidots-esp8266\src\UbiTcp.cpp:312:13: error: aggregate 'tm timeinfo' has incomplete type and cannot be defined
struct tm timeinfo;
^
D:\Arduino\libraries\ubidots-esp8266\src\UbiTcp.cpp:313:27: error: 'gmtime_r' was not declared in this scope
gmtime_r(&now, &timeinfo);
^
D:\Arduino\libraries\ubidots-esp8266\src\UbiTcp.cpp:316:35: error: 'asctime' was not declared in this scope
Serial.print(asctime(&timeinfo));
^
D:\Arduino\libraries\ubidots-esp8266\src\UbiHttp.cpp: In member function 'bool UbiHTTP::_syncronizeTime()':
D:\Arduino\libraries\ubidots-esp8266\src\UbiHttp.cpp:422:28: error: 'time' was not declared in this scope
time_t now = time(nullptr);
^
D:\Arduino\libraries\ubidots-esp8266\src\UbiHttp.cpp:440:13: error: aggregate 'tm timeinfo' has incomplete type and cannot be defined
struct tm timeinfo;
^
D:\Arduino\libraries\ubidots-esp8266\src\UbiHttp.cpp:441:27: error: 'gmtime_r' was not declared in this scope
gmtime_r(&now, &timeinfo);
^
D:\Arduino\libraries\ubidots-esp8266\src\UbiHttp.cpp:444:35: error: 'asctime' was not declared in this scope
Serial.print(asctime(&timeinfo));
^
exit status 1
Error compiling for board LOLIN(WEMOS) D1 R2 & mini.
This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.`

I don't have time to search the whole codebase - which time library should he be using? Is this necessary dependency not mentioned in the documents?

**Comment by jotathebest** [comment]
As time.h is already imported by the[ ESP8266 headers](https://github.com/esp8266/Arduino/blob/af1bc71a9ea09bd92aed033e6a2b6ec2b10c311a/cores/esp8266/time.cpp), there is not need to be explicitly  included in our library, At my side, the TCP example compiles properly so you should check your Arduino installation.

![image](https://user-images.githubusercontent.com/5313567/88492885-a71b6300-cf73-11ea-8a77-ee761534c95d.png)


All the best

**Comment by philbowles** [comment]
"As time.h is already imported by the ESP8266 headers"

What, pray are "the ESP8266 headers" ? do you mean "Arduino.h"
