### ISSUE TITLE
ubidots.get() does not return last value properly

### ISSUE THREAD

**Issue by kyraex** [ubidots/ubidots-esp8266#47]
Greetings,

I am trying to get a last value from a variable within a device using get(DEVICE_LABEL, VARIABLE_LABEL) but it does not return the expected value. When I entered the API url manually it returns the correct value.

In summary
get() command from this library -> returns incorrect value
### Output ###
Connecting to industrial.api.ubidots.com
Ubidots server certificate verified
Requesting to URL: /api/v1.6/devices/{device-name}/{variable-name}/lv
Request sent
GET /api/v1.6/devices/{device-name}/{variable-name}/lv HTTP/1.1
Host: industrial.api.ubidots.com
X-Auth-Token: {token}
User-Agent: UbidotsESP8266/3.0.1
Content-Type: application/json
Connection: close

Length: 0
Value: 0.000000

https://industrial.api.ubidots.com/api/v1.6/devices/{device-name}/{variable-name}/lv?token={token} -> returns correct value
### Output ###
[1.0]

Any thoughts?

**Comment by jotathebest** [comment]
solved at https://github.com/ubidots/ubidots-esp8266/pull/48
