### ISSUE TITLE
Add support to custom timestamp along with value

### ISSUE THREAD

**Issue by initdav** [ubidots/ubidots-esp8266#5]

**Comment by Metavix** [comment]
@juanda95  We are working on that!

**Comment by petergiskes** [comment]
The code is not correct. Line 134 and 135 reads:
        if ((val+currentValue)->timestamp != NULL) {
            sprintf(data, "%s@%s", data, (val+currentValue)->timestamp);

It should be:
        if ((val+i)->timestamp != NULL) {
            sprintf(data, "%s@%u", data, (val+i)->timestamp);
The formatting string %u  I'm not sure of, but %s leads to runtime error.

**Comment by petergiskes** [comment]
Also in the GetValue routine two 8 bit integers are used.
This was a problem when I connected to a public wifi networ and received responses longer than 256 bytes.
